/* Auto-generated by genmsg_cpp for file /home/joschu/Dropbox/myros/verb_msgs/srv/Push.srv */
#ifndef VERB_MSGS_SERVICE_PUSH_H
#define VERB_MSGS_SERVICE_PUSH_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "sensor_msgs/PointCloud2.h"



namespace verb_msgs
{
template <class ContainerAllocator>
struct PushRequest_ {
  typedef PushRequest_<ContainerAllocator> Type;

  PushRequest_()
  : point_cloud()
  {
  }

  PushRequest_(const ContainerAllocator& _alloc)
  : point_cloud(_alloc)
  {
  }

  typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _point_cloud_type;
   ::sensor_msgs::PointCloud2_<ContainerAllocator>  point_cloud;


  typedef boost::shared_ptr< ::verb_msgs::PushRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::verb_msgs::PushRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PushRequest
typedef  ::verb_msgs::PushRequest_<std::allocator<void> > PushRequest;

typedef boost::shared_ptr< ::verb_msgs::PushRequest> PushRequestPtr;
typedef boost::shared_ptr< ::verb_msgs::PushRequest const> PushRequestConstPtr;


template <class ContainerAllocator>
struct PushResponse_ {
  typedef PushResponse_<ContainerAllocator> Type;

  PushResponse_()
  : success(false)
  {
  }

  PushResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::verb_msgs::PushResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::verb_msgs::PushResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PushResponse
typedef  ::verb_msgs::PushResponse_<std::allocator<void> > PushResponse;

typedef boost::shared_ptr< ::verb_msgs::PushResponse> PushResponsePtr;
typedef boost::shared_ptr< ::verb_msgs::PushResponse const> PushResponseConstPtr;

struct Push
{

typedef PushRequest Request;
typedef PushResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Push
} // namespace verb_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::verb_msgs::PushRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::verb_msgs::PushRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::verb_msgs::PushRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d8288ab03c94033ddae07988baace1f7";
  }

  static const char* value(const  ::verb_msgs::PushRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd8288ab03c94033dULL;
  static const uint64_t static_value2 = 0xdae07988baace1f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::verb_msgs::PushRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "verb_msgs/PushRequest";
  }

  static const char* value(const  ::verb_msgs::PushRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::verb_msgs::PushRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sensor_msgs/PointCloud2 point_cloud\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
\n\
";
  }

  static const char* value(const  ::verb_msgs::PushRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::verb_msgs::PushResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::verb_msgs::PushResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::verb_msgs::PushResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::verb_msgs::PushResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::verb_msgs::PushResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "verb_msgs/PushResponse";
  }

  static const char* value(const  ::verb_msgs::PushResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::verb_msgs::PushResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const  ::verb_msgs::PushResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::verb_msgs::PushResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::verb_msgs::PushRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.point_cloud);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PushRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::verb_msgs::PushResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PushResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<verb_msgs::Push> {
  static const char* value() 
  {
    return "d8a44488cb0d26162ce3bf52b99ef2dd";
  }

  static const char* value(const verb_msgs::Push&) { return value(); } 
};

template<>
struct DataType<verb_msgs::Push> {
  static const char* value() 
  {
    return "verb_msgs/Push";
  }

  static const char* value(const verb_msgs::Push&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<verb_msgs::PushRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d8a44488cb0d26162ce3bf52b99ef2dd";
  }

  static const char* value(const verb_msgs::PushRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<verb_msgs::PushRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "verb_msgs/Push";
  }

  static const char* value(const verb_msgs::PushRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<verb_msgs::PushResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d8a44488cb0d26162ce3bf52b99ef2dd";
  }

  static const char* value(const verb_msgs::PushResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<verb_msgs::PushResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "verb_msgs/Push";
  }

  static const char* value(const verb_msgs::PushResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // VERB_MSGS_SERVICE_PUSH_H

